FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app


COPY "MovSharkApi/MovSharkApi/MovSharkApi.csproj" ./MovSharkApi/
RUN dotnet restore ./MovSharkApi/MovSharkApi.csproj


COPY "MovSharkApi/MovSharkApi/" ./MovSharkApi/
RUN dotnet publish ./MovSharkApi/MovSharkApi.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 80
ENTRYPOINT ["dotnet", "MovSharkApi.dll"]
