apiVersion: apps/v1
kind: Deployment
metadata:
  name: movshark-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: movshark-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
